# Generated by Django 2.2 on 2020-01-08 12:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.png/', upload_to=users.models.profile_image),
        ),
    ]
