# Generated by Django 2.2 on 2020-01-12 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200108_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.CharField(default='No', max_length=3)),
                ('friend_req_sent', models.CharField(default='No', max_length=3)),
                ('mtom', models.ManyToManyField(related_name='_friends_mtom_+', to='users.Friends')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
