# Generated by Django 2.2 on 2020-01-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200108_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.CharField(default='No', max_length=3)),
                ('friend_req_sent', models.CharField(default='No', max_length=3)),
            ],
        ),
    ]
