# Generated by Django 2.2 on 2020-01-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user',
            new_name='ruser',
        ),
        migrations.AddField(
            model_name='friends',
            name='auser_id',
            field=models.IntegerField(null=True),
        ),
    ]
