# Generated by Django 2.2 on 2020-01-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
